export type Zone =
  | "Mogu'shan Vaults"
  | "Throne of Thunder"
  | "Siege of Orgrimmar"
  | "Heart of Fear"
  | "Terrace of Endless Spring"
  | "Ahn'Qiraj"
  | "Scarlet Halls"
  | "The Jade Forest"
  | "Stormstout Brewery"
  | "Temple of the Jade Serpent"
  | "Blackwing Lair"
  | "Kun-Lai Summit"
  | "Vale of Eternal Blossoms"
  | "Black Temple"
  | "Karazhan"
  | "Scholomance"
  | "Dread Wastes"
  | "Dragon Soul"
  | "Isle of Thunder"
  | "Timeless Isle"
  | "Mogu'shan Palace"
  | "Isle of Giants"
  | "Scarlet Monastery"
  | "Tempest Keep"
  | "The Wandering Isle"
  | "Naxxramas"
  | "Serpentshrine Cavern"
  | "Molten Core"
  | "Townlong Steppes"
  | "Gate of the Setting Sun"
  | "Valley of the Four Winds"
  | "Grim Batol"
  | "Zul'Gurub"
  | "Mount Hyjal"
  | "Shado-Pan Monastery"
  | "Siege of Niuzao Temple"
  | "Tol Barad"
  | "Well of Eternity"
  | "Twilight Highlands"
  | "Hellfire Peninsula"
  | "Molten Front"
  | "Hellfire Ramparts"
  | "Hour of Twilight"
  | "Blackrock Depths"
  | "Krasarang Wilds"
  | "Thousand Needles"
  | "Ruins of Ahn'Qiraj"
  | "Northern Stranglethorn"
  | "Blasted Lands"
  | "Echo Isles"
  | "Northern Barrens"
  | "Onyxia's Lair"
  | "Sunwell Plateau"
  | "Stratholme"
  | "Uldum"
  | "Tanaris"
  | "Shrine of Seven Stars"
  | "Duskwood"
  | "Ashenvale"
  | "Eastern Plaguelands"
  | "Silverpine Forest"
  | "Dire Maul"
  | "Wintergrasp"
  | "Blackrock Spire"
  | "Winterspring"
  | "Un'Goro Crater"
  | "The Botanica"
  | "Deepholm"
  | "Scarlet Monastery"
  | "Silithus"
  | "Swamp of Sorrows"
  | "Zul'Aman"
  | "Hillsbrad Foothills"
  | "Shadowmoon Valley"
  | "The Veiled Stair"
  | "Zangarmarsh"
  | "Terokkar Forest"
  | "Orgrimmar"
  | "The Stonecore"
  | "Stonetalon Mountains"
  | "Firelands"
  | "The Cape of Stranglethorn"
  | "Feralas"
  | "Vashj'ir"
  | "Brawl'gar Arena"
  | "Gruul's Lair"
  | "Badlands"
  | "Felwood"
  | "Sethekk Halls"
  | "Burning Steppes"
  | "Isle of Quel'Danas"
  | "Magisters' Terrace"
  | "The Deadmines"
  | "Arathi Highlands"
  | "Halls of Origination"
  | "Darkmoon Island"
  | "Hyjal Summit"
  | "End Time"
  | "Dustwallow Marsh"
  | "Western Plaguelands"
  | "Ulduar"
  | "Netherstorm"
  | "Sholazar Basin"
  | "Stormwind City"
  | "Mana-Tombs"
  | "The Storm Peaks"
  | "Shattrath City"
  | "The Temple of Atal'Hakkar"
  | "Gnomeregan"
  | "The Blood Furnace"
  | "Gundrak"
  | "The Obsidian Sanctum"
  | "The Stockade"
  | "Blackfathom Deeps"
  | "Nagrand"
  | "ScholomanceOLD"
  | "Ragefire Chasm"
  | "Lost City of the Tol'vir"
  | "Howling Fjord"
  | "Magtheridon's Lair"
  | "Razorfen Kraul"
  | "Uldaman"
  | "Desolace"
  | "Pit of Saron"
  | "Silvershard Mines"
  | "Zul'Farrak"
  | "Icecrown"
  | "Blade's Edge Mountains"
  | "Searing Gorge"
  | "Shadowfang Keep"
  | "Blackrock Caverns"
  | "Azshara"
  | "Razorfen Downs"
  | "Redridge Mountains"
  | "Theramore's Fall"
  | "Tirisfal Glades"
  | "Wailing Caverns"
  | "Utgarde Pinnacle"
  | "Coldridge Valley"
  | "The Vortex Pinnacle"
  | "Dragonblight"
  | "New Tinkertown"
  | "The Hinterlands"
  | "Wetlands"
  | "Azjol-Nerub"
  | "Icecrown Citadel"
  | "Grizzly Hills"
  | "The Shattered Halls"
  | "Shimmering Expanse"
  | "Southern Barrens"
  | "Westfall"
  | "Crusaders' Coliseum: Trial of the Champion"
  | "Deadwind Pass"
  | "Elwynn Forest"
  | "Utgarde Keep"
  | "Darkshore"
  | "The Eye of Eternity"
  | "Borean Tundra"
  | "Halls of Lightning"
  | "Deepwind Gorge"
  | "The Arcatraz"
  | "Crusaders' Coliseum: Trial of the Crusader"
  | "The Forge of Souls"
  | "Chapel Gardens"
  | "Loch Modan"
  | "Deathknell"
  | "Zul'Drak"
  | "Celestial Tournament"
  | "Undercity"
  | "Stranglethorn Vale"
  | "Proving Grounds"
  | "Tol Barad Peninsula"
  | "Silvermoon City"
  | "The Slave Pens"
  | "Darnassus"
  | "Durotar"
  | "The Bastion of Twilight"
  | "Unga Ingoo"
  | "Northshire"
  | "Sunstrider Isle"
  | "Vault of Archavon"
  | "Dalaran"
  | "Ahn'kahet: The Old Kingdom"
  | "Gilneas"
  | "Throne of the Tides"
  | "Throne of the Four Winds"
  | "Arena of Annihilation"
  | "Azuremyst Isle"
  | "Baradin Hold"
  | "Mulgore"
  | "The Steamvault"
  | "Auchenai Crypts"
  | "Drak'Tharon Keep"
  | "Halls of Stone"
  | "The Black Morass"
  | "Maraudon"
  | "Camp Narache"
  | "The Underbog"
  | "The Culling of Stratholme"
  | "Tol'viron Arena"
  | "Thunder King's Citadel"
  | "Ghostlands"
  | "The Nexus"
  | "The Oculus"
  | "Dustwallow Marsh"
  | "Moonglade"
  | "Forlorn Cloister"
  | "Crypt of Forgotten Kings"
  | "Halls of Reflection"
  | "Ironforge"
  | "Shadow Labyrinth"
  | "Eversong Woods"
  | "Dun Morogh"
  | "Teldrassil"
  | "Shadowglen"
  | "Old Hillsbrad Foothills"
  | "The Violet Hold"
  | "Ahn'Qiraj: The Fallen Kingdom"
  | "Warsong Gulch"
  | "Blackrock Mountain"
  | "The Halfhill Market"
  | "Kelp'thar Forest"
  | "Temple of Kotmogu"
  | "Abyssal Depths"
  | "Caverns of Time"
  | "Valley of Trials"
  | "The Exodar"
  | "Abyssal Maw"
  | "Bloodmyst Isle"
  | "Nagrand Arena (Nagrand Arena)"
  | "Thunder Bluff"
  | "The Tiger's Peak"
  | "Blackwing Descent"
  | "The Jade Forest"
  | "The Mechanar"
  | "Battle on the High Seas"
  | "Gilneas City"
  | "The Lost Isles"
  | "Dalaran"
  | "Ruins of Lordaeron (Undercity Arena)"
  | "The Frozen Throne"
  | "A Little Patience"
  | "Ruins of Gilneas"
  | "Alcaz Island"
  | "Temple of Kotmogu"
  | "Black Temple"
  | "Azure Dragonshrine"
  | "Dustwallow Marsh"
  | "Eye of the Storm"
  | "Ammen Vale"
  | "Vale of Eternal Blossoms"
  | "Gilneas (Do Not Reuse)"
  | "Hrothgar's Landing"
  | "The Ruby Sanctum"
  | "A Brewing Storm"
  | "The Secrets of Ragefire"
  | "Isle of Thunder"
  | "Alterac Valley"
  | "Ruby Dragonshrine"
  | "Alliance Mercenary Ship to Vashj'ir"
  | "Sholazar Basin"
  | "Dev Smoketest Area"
  | "Isle of Conquest"
  | "The Great Sea"
  | "Kezan"
  | "Arathi Basin"
  | "CTF3"
  | "Dagger in the Dark"
  | "Battle for Wintergrasp"
  | "Class Quest"
  | "Crystalsong Forest"
  | "Greenstone Village"
  | "Hyjal Past"
  | "Krasarang Wilds"
  | "Steelspark Station"
  | "Isle of Thunder"
  | "Battle for Tol Barad"
  | "Deeprun Tram"
  | "The Battle for Gilneas"
  | "Krasarang Wilds"
  | "Kun-Lai Summit"
  | "The Maelstrom"
  | "The Frost Queen's Lair"
  | "To The Skies!"
  | "Transport: Horde Gunship (IGB)"
  | "Ahn'Qiraj Terrace"
  | "Brian and Pat Test"
  | "Dalaran Arena (Arena)"
  | "Spine of the Destroyer UNUSED"
  | "Bronze Dragonshrine"
  | "The North Sea"
  | "The Ring of Valor (Orgrimmar Arena)"
  | "Siege of Orgrimmar (OLD DO NOT USE)"
  | "Putricide's Laboratory of Alchemical Horrors and Fun"
  | "Blood in the Snow"
  | "Maelstrom Deathwing Fight"
  | "Infiltrating the Shipyard"
  | "The Lost Isles"
  | "Seat of Life"
  | "Twin Peaks"
  | "Tol Barad Peninsula"
  | "Twisting Nether"
  | "Blade's Edge Arena (Blade's Edge Arena)"
  | "Brewmoon Festival"
  | "Dustwallow Marsh"
  | "Eye of the Storm"
  | "Strand of the Ancients"
  | "SM Cathedral/GY (TEMP)"
  | "Emerald Dragonshrine"
  | "The Frozen Sea"
  | "The Secret Ingredient"
  | "The Maelstrom"
  | "Plaguelands: The Scarlet Enclave"
  | "[TEMP] JT"
  | "Testing02"
  | "Transport: Horde Gunship"
  | "Assault on Zan'vess"
  | "Development Land"
  | "Domination Point"
  | "Obsidian Dragonshrine"
  | "Test Dungeon"
  | "Emerald Forest"
  | "Ruins of Gilneas City"
  | "Force Interior"
  | "Lion's Landing"
  | "Nightmare Scar"
  | "Dark Heart of Pandaria"
  | "The Sanctum of Blood"
  | "Scenario - Mogu Ruins"
  | "Scenario - Black Ox Temple"
  | "Valley Of Power - Scenario"
  | "Cleft of Shadow"
  | "Slitherblade Shore"
  | "Black Ox Temple"
  | "Transport: Alliance Gunship"
  | "The Veiled Sea"
  | "Vordrassil's Tears"
  | "Defense of the Alehouse"
  | "Storm Cliffs"
  | "Icecrown"
  | "Reuse Me 7"
  | "Auchindoun"
  | "Dragonblight"
  | "The Battle for Gilneas (Old City Map)"
  | "Dun Morogh"
  | "The Nexus"
  | "The North Sea"
  | "The North Sea"
  | "Stromgarde Keep"
  | "Transport: Alliance Gunship (IGB)"
  | "Borean Tundra"
  | "The Crimson Hall"
  | "The Park"
  | "Transport: Onyxia/Nefarian Elevator"
  | "Azjol-Nerub"
  | "Sunken Temple";
